#!/bin/bash

    CC=aarch64-linux-gnu-gcc \
    CXX=aarch64-linux-gnu-g++ \
    PKG_CONFIG=aarch64-linux-gnu-pkg-config \
	USE_CODEC_VORBIS=0 \
	USE_CODEC_OPUS=0 \
	USE_CURL=0 \
	USE_CURL_DLOPEN=0 \
	USE_OPENAL=1 \
	USE_OPENAL_DLOPEN=1 \
	USE_RENDERER_DLOPEN=0 \
	USE_VOIP=0 \
	USE_LOCAL_HEADERS=1 \
	USE_INTERNAL_JPEG=1 \
	USE_INTERNAL_OPUS=1 \
	USE_INTERNAL_ZLIB=1 \
	USE_OPENGLES=1 \
	USE_BLOOM=0 \
    USE_AUTOAIM=1 \
	USE_MUMBLE=0 \
	BUILD_GAME_SO=1 \
	BUILD_RENDERER_REND2=0 \
	ARCH=aarch64 \
	PLATFORM=linux \
	COMPILE_ARCH=x86_64 \
	COMPILE_PLATFORM=linux \
	make $*